### ISSUE TITLE
Get Dapp directory working with updated node version

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/ovm-og-multisigwallet#5]

**Comment by wildmolasses** [comment]
i'm not optimistic about upgrading this to node >12. while we determine whether it's necessary, I'm wondering if we can get away with using node 6 via volta and making volta required.

As far as UX goes, how should we imagine users consuming this dapp? should we expect them to pull the repo down and run the dapp via command line? gnosis was publishing electron builds on their repo. are we thinking about doing the same? or should we expect users to use a hosted version of this wallet only? Is that even an option given gnosis's injunction against using the hosted version for signing?

**Comment by apbendi** [comment]
> i'm not optimistic about upgrading this to node >12. while we determine whether it's necessary, I'm wondering if we can get away with using node 6 via volta and making volta required.

Were you able to get the frontend running w/o upgrading the node version? If so, I think we can get away with it, as long as we triage the dependencies and make sure there aren't any critical security vulnerabilities in outdated versions. The other question is the web3 version. Right now the frontend uses the long deprecated injected web3. At a minimum, we need to update that.

> As far as UX goes, how should we imagine users consuming this dapp? 

All good questions.

> gnosis's injunction against using the hosted version for signing

Can you remind me what you're referring to here?

I'd been imagining we'd offer a hosted version, but maybe that's a bad idea. If so, having a simple npm command to get it working and pointed at mainnet Optimistic Ethereum might be the best option. For example, running `npm run dapp --network optimism` or something like that.

**Comment by wildmolasses** [comment]
> Can you remind me what you're referring to here?

Here are the terms that pop up on first load

![Screen Shot 2021-02-16 at 11 36 53 AM](https://user-images.githubusercontent.com/5423313/108100251-48baec80-704b-11eb-8942-6788129e7b19.png)

**Comment by apbendi** [comment]
Canceled in favor of #18
